---
abstract: 'Cluster operations based on parallel SSH, set and interval arithmetic'
author:
  - "Zhang \"agentzh\" Yichun <agentzh@gmail.com>"
build_requires:
  ExtUtils::MakeMaker: 6.42
  IPC::Run3: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SSH-Batch
no_index:
  directory:
    - inc
    - t
requires:
  File::HomeDir: 0
  File::Temp: 0
  Filter::Util::Call: 0
  IO::Pty: 0
  Net::OpenSSH: 0.34
  Set::Scalar: 1.23
  Term::ReadKey: 2.30
  perl: 5.6.1
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository: http://github.com/agentzh/sshbatch
version: 0.027
